Issue 113 d2
dgidb/dgidb-v5 pull request #126
Opened 2022-05-13 12:56 UTC by mcannon068nw

Fixes #113

2022-05-13 12:58 UTC, mcannon068nw commented
recovered TSV added to s3

2022-05-17 12:54 UTC, jsstevenson requested changes

2022-05-17 12:54 UTC, jsstevenson commented on server/lib/genome/importers/file_importers/nci.rb
> +      @file_path = file_path
should be `@file_path = handle_file_location file_path`

2022-05-17 12:54 UTC, jsstevenson commented on server/lib/genome/importers/file_importers/nci.rb
> +              source_db_version:  get_version,
`get version` should be deleted and we should be hardcoding the data date. Last update on dgidb is listed as "14-September-2017" so we can probably use that

2022-05-17 12:57 UTC, jsstevenson commented
Oh, one other thing

in lib/tasks/importers.rake, you should delete lines 136 and 137 

```
      # TODO: remove WIP importers
      adj_file_importer_names = file_importer_names.reject { |name| name == 'nci' }
```

so that NCI gets added back into the working importers list

2022-05-17 13:52 UTC, jsstevenson requested changes

2022-05-17 13:52 UTC, jsstevenson commented on server/lib/genome/importers/file_importers/nci.rb
> +      create_interaction_claims
this method name should be changed to `create_claims` and the `remove_existing_source` and `create_new_source` lines should be deleted

2022-05-17 14:31 UTC, jsstevenson requested changes

2022-05-17 14:31 UTC, jsstevenson commented on server/lib/genome/importers/file_importers/nci.rb
> +      Utils::Database.delete_source('NCI')
this method isn't used, can be deleted

2022-05-17 14:31 UTC, jsstevenson commented on server/lib/genome/importers/file_importers/nci.rb
> +      @new_version = source_db_version
no longer used, can be deleted

2022-05-17 18:28 UTC, jsstevenson approved these changes

2022-05-17 18:29 UTC, merged